---

- name: Git config XonqNopp
  ansible.builtin.git:
    cmd:  # TODO
    - config --local user.name XonqNopp
    - config --local user.email xonqnoppp@gmail.com
    - remote rename origin upstream  # fails if already applied
