- name: Install shell packages
  ansible.builtin.apt:
    pkg:
    - git
    - git-lfs
    - git-gui
    - gitk
    - vim
    - python3
    - python3-pip

- name: Install python base tools
  ansible.builtin.pip:
    name:
    - pip
    - setuptools
    - pylint
    - mypy
    state: latest
